In [1]:
import pandas as pd
import numpy as np
import math
import statsmodels.api as sm

In [2]:
df = pd.read_excel('Gadarwara_Q.xlsx')
df

Dates  Year  Month  Day  RF_1  RF_2  RF_3  RF_3(t-1)  RF_3(t-2)  \
0     1977-06-01  1977      6    1   0.0   0.0   0.0        0.0        0.0   
1     1977-06-02  1977      6    2   0.0   0.0   0.0        0.0        0.0   
2     1977-06-03  1977      6    3   0.0   0.0   0.0        0.0        0.0   
3     1977-06-04  1977      6    4   0.0   0.0   0.0        0.0        0.0   
4     1977-06-05  1977      6    5   0.0   0.0   0.0        0.0        0.0   
...          ...   ...    ...  ...   ...   ...   ...        ...        ...   
15701 2020-05-27  2020      5   27   0.0   0.0   0.0        0.0        0.0   
15702 2020-05-28  2020      5   28   0.0   0.0   0.0        0.0        0.0   
15703 2020-05-29  2020      5   29   0.0   0.0   0.0        0.0        0.0   
15704 2020-05-30  2020      5   30   1.1   0.3   0.0        0.0        0.0   
15705 2020-05-31  2020      5   31   0.0   0.0   0.0        0.0        0.0   

       RF_4  ...  Unnamed: 35  Unnamed: 36  Unnamed: 37  Unnamed: 38  \
0       0.0  ...          NaN          NaN          NaN          NaN   
1       0.0  ...          NaN          NaN          NaN          NaN   
2       0.0  ...          NaN          NaN          NaN          NaN   
3       0.0  ...          NaN          NaN          NaN          NaN   
4       0.0  ...          NaN          NaN          NaN          NaN   
...     ...  ...          ...          ...          ...          ...   
15701   0.0  ...          NaN          NaN          NaN          NaN   
15702   0.0  ...          NaN          NaN          NaN          NaN   
15703   0.0  ...          NaN          NaN          NaN          NaN   
15704   0.3  ...          NaN          NaN          NaN          NaN   
15705   0.0  ...          NaN          NaN          NaN          NaN   

       Unnamed: 39  Unnamed: 40  Unnamed: 41  Unnamed: 42  Grid Point  \
0              NaN          NaN          NaN          NaN        RF_1   
1              NaN          NaN          NaN          NaN        RF_2   
2              NaN          NaN          NaN          NaN        RF_3   
3              NaN          NaN          NaN          NaN        RF_4   
4              NaN          NaN          NaN          NaN        RF_5   
...            ...          ...          ...          ...         ...   
15701          NaN          NaN          NaN          NaN         NaN   
15702          NaN          NaN          NaN          NaN         NaN   
15703          NaN          NaN          NaN          NaN         NaN   
15704          NaN          NaN          NaN          NaN         NaN   
15705          NaN          NaN          NaN          NaN         NaN   

        weights  
0      0.013302  
1      0.010567  
2      0.086394  
3      0.273084  
4      0.104194  
...         ...  
15701       NaN  
15702       NaN  
15703       NaN  
15704       NaN  
15705       NaN  

[15706 rows x 45 columns]

In [3]:
part1 = df.drop(df.index[12418:15706])
part2 = df.drop(df.index[0:12418])
print(part1.shape, part2.shape)

(12418, 45) (3288, 45)


In [4]:
part1

Dates  Year  Month  Day  RF_1  RF_2  RF_3  RF_3(t-1)  RF_3(t-2)  \
0     1977-06-01  1977      6    1   0.0   0.0   0.0        0.0        0.0   
1     1977-06-02  1977      6    2   0.0   0.0   0.0        0.0        0.0   
2     1977-06-03  1977      6    3   0.0   0.0   0.0        0.0        0.0   
3     1977-06-04  1977      6    4   0.0   0.0   0.0        0.0        0.0   
4     1977-06-05  1977      6    5   0.0   0.0   0.0        0.0        0.0   
...          ...   ...    ...  ...   ...   ...   ...        ...        ...   
12413 2011-05-27  2011      5   27   0.0   0.0   0.0        1.4        1.5   
12414 2011-05-28  2011      5   28   0.0   0.0   0.0        0.0        1.4   
12415 2011-05-29  2011      5   29   0.0   0.0   0.0        0.0        0.0   
12416 2011-05-30  2011      5   30   0.0   0.0   0.0        0.0        0.0   
12417 2011-05-31  2011      5   31   0.0   0.0   0.0        0.0        0.0   

       RF_4  ...  Unnamed: 35  Unnamed: 36  Unnamed: 37  Unnamed: 38  \
0       0.0  ...          NaN          NaN          NaN          NaN   
1       0.0  ...          NaN          NaN          NaN          NaN   
2       0.0  ...          NaN          NaN          NaN          NaN   
3       0.0  ...          NaN          NaN          NaN          NaN   
4       0.0  ...          NaN          NaN          NaN          NaN   
...     ...  ...          ...          ...          ...          ...   
12413   0.0  ...          NaN          NaN          NaN          NaN   
12414   0.0  ...          NaN          NaN          NaN          NaN   
12415   0.0  ...          NaN          NaN          NaN          NaN   
12416   0.0  ...          NaN          NaN          NaN          NaN   
12417   0.0  ...          NaN          NaN          NaN          NaN   

       Unnamed: 39  Unnamed: 40  Unnamed: 41  Unnamed: 42  Grid Point  \
0              NaN          NaN          NaN          NaN        RF_1   
1              NaN          NaN          NaN          NaN        RF_2   
2              NaN          NaN          NaN          NaN        RF_3   
3              NaN          NaN          NaN          NaN        RF_4   
4              NaN          NaN          NaN          NaN        RF_5   
...            ...          ...          ...          ...         ...   
12413          NaN          NaN          NaN          NaN         NaN   
12414          NaN          NaN          NaN          NaN         NaN   
12415          NaN          NaN          NaN          NaN         NaN   
12416          NaN          NaN          NaN          NaN         NaN   
12417          NaN          NaN          NaN          NaN         NaN   

        weights  
0      0.013302  
1      0.010567  
2      0.086394  
3      0.273084  
4      0.104194  
...         ...  
12413       NaN  
12414       NaN  
12415       NaN  
12416       NaN  
12417       NaN  

[12418 rows x 45 columns]

In [5]:
part2

Dates  Year  Month  Day  RF_1  RF_2  RF_3  RF_3(t-1)  RF_3(t-2)  \
12418 2011-06-01  2011      6    1   0.0   0.0   0.0        0.0        0.0   
12419 2011-06-02  2011      6    2   0.0   0.0   0.0        0.0        0.0   
12420 2011-06-03  2011      6    3   0.0   0.0   0.0        0.0        0.0   
12421 2011-06-04  2011      6    4  16.9  10.7   3.2        0.0        0.0   
12422 2011-06-05  2011      6    5   0.0   0.0   0.0        3.2        0.0   
...          ...   ...    ...  ...   ...   ...   ...        ...        ...   
15701 2020-05-27  2020      5   27   0.0   0.0   0.0        0.0        0.0   
15702 2020-05-28  2020      5   28   0.0   0.0   0.0        0.0        0.0   
15703 2020-05-29  2020      5   29   0.0   0.0   0.0        0.0        0.0   
15704 2020-05-30  2020      5   30   1.1   0.3   0.0        0.0        0.0   
15705 2020-05-31  2020      5   31   0.0   0.0   0.0        0.0        0.0   

       RF_4  ...  Unnamed: 35  Unnamed: 36  Unnamed: 37  Unnamed: 38  \
12418   0.0  ...          NaN          NaN          NaN          NaN   
12419   0.0  ...          NaN          NaN          NaN          NaN   
12420   0.0  ...          NaN          NaN          NaN          NaN   
12421   0.0  ...          NaN          NaN          NaN          NaN   
12422   0.0  ...          NaN          NaN          NaN          NaN   
...     ...  ...          ...          ...          ...          ...   
15701   0.0  ...          NaN          NaN          NaN          NaN   
15702   0.0  ...          NaN          NaN          NaN          NaN   
15703   0.0  ...          NaN          NaN          NaN          NaN   
15704   0.3  ...          NaN          NaN          NaN          NaN   
15705   0.0  ...          NaN          NaN          NaN          NaN   

       Unnamed: 39  Unnamed: 40  Unnamed: 41  Unnamed: 42  Grid Point  weights  
12418          NaN          NaN          NaN          NaN         NaN      NaN  
12419          NaN          NaN          NaN          NaN         NaN      NaN  
12420          NaN          NaN          NaN          NaN         NaN      NaN  
12421          NaN          NaN          NaN          NaN         NaN      NaN  
12422          NaN          NaN          NaN          NaN         NaN      NaN  
...            ...          ...          ...          ...         ...      ...  
15701          NaN          NaN          NaN          NaN         NaN      NaN  
15702          NaN          NaN          NaN          NaN         NaN      NaN  
15703          NaN          NaN          NaN          NaN         NaN      NaN  
15704          NaN          NaN          NaN          NaN         NaN      NaN  
15705          NaN          NaN          NaN          NaN         NaN      NaN  

[3288 rows x 45 columns]

# MLR STARTS HERE

In [6]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

In [7]:
# independent variable = RF_1 RF_2 RF_3 RF_4 RF_5 RF_6 RF_8 
model1 = linear_model.LinearRegression()
model1.fit(part1[['RF_1', 'RF_2', 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8']], part1.Q)
Q_pred1 = model1.predict(part2[['RF_1', 'RF_2', 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[-0.56505677  1.28876109  1.32884194  0.73779039  1.00862853  4.37721491
  4.41221542] 6.706250158112262 0.009261062282254984 130.9698260063012


In [8]:
# independent variable =  RF_3 RF_4 RF_5 RF_6 RF_8 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[1.11123368 0.97258826 0.87038138 4.38181594 5.26203985] 6.9819462718930225 0.004494252567625923 131.28451995448762


In [9]:
# independent variable =  RF_3 RF_4 RF_5 RF_6 RF_8 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[1.11123368 0.97258826 0.87038138 4.38181594 5.26203985] 6.9819462718930225 0.004494252567625923 131.28451995448762


In [10]:
# independent variable =  RF_3 RF_4 RF_5 RF_6 RF_8 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[1.11123368 0.97258826 0.87038138 4.38181594 5.26203985] 6.9819462718930225 0.004494252567625923 131.28451995448762


In [11]:
# independent variable =  RF_3 RF_4 RF_5 RF_6 RF_8(t-1) 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8(t-1)']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8(t-1)']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[ 3.08955547 -0.65703402  3.14683565  4.60951632  3.25878967] 4.300677008812428 0.15666891504751312 120.83442754260214


In [12]:
# independent variable =  RF_3 RF_4 RF_5 RF_6(t-1) RF_8(t-1) 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6(t-1)', 'RF_8(t-1)']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6(t-1)', 'RF_8(t-1)']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[-0.88282256  3.56946769  6.97709418  2.40396082  1.84404617] 2.702843706934779 0.1944820469301599 118.09438443742114


In [13]:
# independent variable =  RF_3 RF_4 RF_5(t-1) RF_6(t-1) RF_8(t-1) 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3', 'RF_4', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3', 'RF_4', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[6.40551693 2.3616574  0.95890022 1.95596673 1.88198064] 3.4283524482026024 0.22176065413013601 116.07754826864239


In [14]:
# independent variable =  RF_3 RF_4(t-1) RF_5(t-1) RF_6(t-1) RF_8(t-1) 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[ 8.61246129 -0.24724284  0.84940528  2.35963343  1.84693706] 3.93363907287619 0.21673733903201542 116.45156957805976


In [15]:
# independent variable =  RF_3(t-1) RF_4(t-1) RF_5(t-1) RF_6(t-1) RF_8(t-1) 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3(t-1)', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3(t-1)', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[0.25109785 0.59251397 0.48640318 4.22150098 3.26101911] 18.353143472600458 0.30932154406028345 109.35271983986033


In [16]:
 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 't-1', 't-2', 't-3']], part1.Q)
Q_pred1 = model1.predict(part2[[ 't-1', 't-2', 't-3']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[-0.84496595 10.53132877  4.63693917] 1.385449396838247 0.12719889315836552 122.92756493727481


In [20]:
 
model1 = linear_model.LinearRegression()
model1.fit(part1[[  'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)', 't-1']], part1.Q)
Q_pred1 = model1.predict(part2[[  'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)', 't-1']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[-0.43358281  1.39078102  2.70087511  2.80926976  2.4413476 ] 18.03192778445955 0.31236507933657365 109.11151764477428


In [22]:
model1 = linear_model.LinearRegression()
model1.fit(part1[[  'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)', 't-1']], part1.Q)
Q_pred1 = model1.predict(part2[[  'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)', 't-1']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[ 0.06138028  1.21617922  3.32355434  3.14845969 -0.68434807  3.70622889] 12.318833353713046 0.3016843177590871 109.95564544935986
