In [2]:
import pandas as pd
import numpy as np
import math
import statsmodels.api as sm

In [3]:
df = pd.read_excel('Monsoon.xlsx')
df

Unnamed: 0      Dates  Year  Month  Day  RF_1  RF_2  RF_3  RF_3(t-1)  \
0              0 1977-06-01  1977      6    1   0.0   0.0   0.0        0.0   
1              1 1977-06-02  1977      6    2   0.0   0.0   0.0        0.0   
2              2 1977-06-03  1977      6    3   0.0   0.0   0.0        0.0   
3              3 1977-06-04  1977      6    4   0.0   0.0   0.0        0.0   
4              4 1977-06-05  1977      6    5   0.0   0.0   0.0        0.0   
...          ...        ...   ...    ...  ...   ...   ...   ...        ...   
5241       15457 2019-09-26  2019      9   26  21.6  27.2  24.3        4.9   
5242       15458 2019-09-27  2019      9   27   5.3   4.7   1.8       24.3   
5243       15459 2019-09-28  2019      9   28  15.6  10.6  22.4        1.8   
5244       15460 2019-09-29  2019      9   29  25.8  25.2  43.5       22.4   
5245       15461 2019-09-30  2019      9   30   0.4   0.1   3.4       43.5   

      RF_3(t-2)  ...        t-2        t-3        t-4      Q  Q(t-1)  Q(t-2)  \
0           0.0  ...   0.000000   0.000000   0.000000    1.6     0.0     0.0   
1           0.0  ...   0.000000   0.000000   0.000000    1.6     1.6     0.0   
2           0.0  ...   0.000000   0.000000   0.000000    1.6     1.6     1.6   
3           0.0  ...   0.000000   0.000000   0.000000    1.6     1.6     1.6   
4           0.0  ...   0.000000   0.000000   0.000000    1.6     1.6     1.6   
...         ...  ...        ...        ...        ...    ...     ...     ...   
5241        2.6  ...  11.646137   3.809934  10.106873  100.5   199.3    77.1   
5242        4.9  ...   4.281813  11.313970   7.543936  216.0   100.5   199.3   
5243       24.3  ...  22.142039   6.894527  24.506266  138.5   216.0   100.5   
5244        1.8  ...  45.607871  24.295851  44.585217  118.3   138.5   216.0   
5245       22.4  ...   1.880322  38.601032   7.226873  216.0   118.3   138.5   

      Q(t-3)  Unnamed: 34  Grid Point   weights  
0        0.0          NaN        RF_1  0.013302  
1        0.0          NaN        RF_2  0.010567  
2        0.0          NaN        RF_3  0.086394  
3        1.6          NaN        RF_4  0.273084  
4        1.6          NaN        RF_5  0.104194  
...      ...          ...         ...       ...  
5241    86.3          NaN         NaN       NaN  
5242    77.1          NaN         NaN       NaN  
5243   199.3          NaN         NaN       NaN  
5244   100.5          NaN         NaN       NaN  
5245   216.0          NaN         NaN       NaN  

[5246 rows x 38 columns]

In [4]:
part1 = df.drop(df.index[4270:5246])
part2 = df.drop(df.index[0:4270])
print(part1.shape, part2.shape)

(4270, 38) (976, 38)


In [5]:
part1

Unnamed: 0      Dates  Year  Month  Day  RF_1  RF_2  RF_3  RF_3(t-1)  \
0              0 1977-06-01  1977      6    1   0.0   0.0   0.0        0.0   
1              1 1977-06-02  1977      6    2   0.0   0.0   0.0        0.0   
2              2 1977-06-03  1977      6    3   0.0   0.0   0.0        0.0   
3              3 1977-06-04  1977      6    4   0.0   0.0   0.0        0.0   
4              4 1977-06-05  1977      6    5   0.0   0.0   0.0        0.0   
...          ...        ...   ...    ...  ...   ...   ...   ...        ...   
4265       12535 2011-09-26  2011      9   26   0.0   0.0   0.0        0.0   
4266       12536 2011-09-27  2011      9   27   0.0   0.0   0.0        0.0   
4267       12537 2011-09-28  2011      9   28   0.0   0.0   0.0        0.0   
4268       12538 2011-09-29  2011      9   29   0.0   0.0   0.0        0.0   
4269       12539 2011-09-30  2011      9   30   0.0   0.0   0.0        0.0   

      RF_3(t-2)  ...  t-2  t-3  t-4          Q     Q(t-1)     Q(t-2)  \
0           0.0  ...  0.0  0.0  0.0   1.600000   0.000000   0.000000   
1           0.0  ...  0.0  0.0  0.0   1.600000   1.600000   0.000000   
2           0.0  ...  0.0  0.0  0.0   1.600000   1.600000   1.600000   
3           0.0  ...  0.0  0.0  0.0   1.600000   1.600000   1.600000   
4           0.0  ...  0.0  0.0  0.0   1.600000   1.600000   1.600000   
...         ...  ...  ...  ...  ...        ...        ...        ...   
4265        0.0  ...  0.0  0.0  0.0  47.799088  69.457275  97.324950   
4266        0.0  ...  0.0  0.0  0.0  46.781605  47.799088  69.457275   
4267        0.0  ...  0.0  0.0  0.0  45.136337  46.781605  47.799088   
4268        0.0  ...  0.0  0.0  0.0  45.113705  45.136337  46.781605   
4269        0.0  ...  0.0  0.0  0.0  34.133636  45.113705  45.136337   

          Q(t-3)  Unnamed: 34  Grid Point   weights  
0       0.000000          NaN        RF_1  0.013302  
1       0.000000          NaN        RF_2  0.010567  
2       0.000000          NaN        RF_3  0.086394  
3       1.600000          NaN        RF_4  0.273084  
4       1.600000          NaN        RF_5  0.104194  
...          ...          ...         ...       ...  
4265  110.654434          NaN         NaN       NaN  
4266   97.324950          NaN         NaN       NaN  
4267   69.457275          NaN         NaN       NaN  
4268   47.799088          NaN         NaN       NaN  
4269   46.781605          NaN         NaN       NaN  

[4270 rows x 38 columns]

In [6]:
part2

Unnamed: 0      Dates  Year  Month  Day  RF_1  RF_2  RF_3  RF_3(t-1)  \
4270       12784 2012-06-01  2012      6    1   0.0   0.0   0.0        0.0   
4271       12785 2012-06-02  2012      6    2   2.7   0.3   1.5        0.0   
4272       12786 2012-06-03  2012      6    3   0.0   0.0   0.3        1.5   
4273       12787 2012-06-04  2012      6    4   0.0   0.0   0.0        0.3   
4274       12788 2012-06-05  2012      6    5   0.0   0.0   0.0        0.0   
...          ...        ...   ...    ...  ...   ...   ...   ...        ...   
5241       15457 2019-09-26  2019      9   26  21.6  27.2  24.3        4.9   
5242       15458 2019-09-27  2019      9   27   5.3   4.7   1.8       24.3   
5243       15459 2019-09-28  2019      9   28  15.6  10.6  22.4        1.8   
5244       15460 2019-09-29  2019      9   29  25.8  25.2  43.5       22.4   
5245       15461 2019-09-30  2019      9   30   0.4   0.1   3.4       43.5   

      RF_3(t-2)  ...        t-2        t-3        t-4      Q  Q(t-1)  Q(t-2)  \
4270        0.0  ...   0.000000   0.000000   0.000000    0.0     0.0     0.0   
4271        0.0  ...   1.107002   0.116698   0.555159    0.0     0.0     0.0   
4272        0.0  ...   0.023359   1.069968   0.111489    0.0     0.0     0.0   
4273        1.5  ...   0.003295   0.004006   0.003521    0.0     0.0     0.0   
4274        0.3  ...   0.000000   0.000000   0.000000    0.0     0.0     0.0   
...         ...  ...        ...        ...        ...    ...     ...     ...   
5241        2.6  ...  11.646137   3.809934  10.106873  100.5   199.3    77.1   
5242        4.9  ...   4.281813  11.313970   7.543936  216.0   100.5   199.3   
5243       24.3  ...  22.142039   6.894527  24.506266  138.5   216.0   100.5   
5244        1.8  ...  45.607871  24.295851  44.585217  118.3   138.5   216.0   
5245       22.4  ...   1.880322  38.601032   7.226873  216.0   118.3   138.5   

      Q(t-3)  Unnamed: 34  Grid Point  weights  
4270     0.0          NaN         NaN      NaN  
4271     0.0          NaN         NaN      NaN  
4272     0.0          NaN         NaN      NaN  
4273     0.0          NaN         NaN      NaN  
4274     0.0          NaN         NaN      NaN  
...      ...          ...         ...      ...  
5241    86.3          NaN         NaN      NaN  
5242    77.1          NaN         NaN      NaN  
5243   199.3          NaN         NaN      NaN  
5244   100.5          NaN         NaN      NaN  
5245   216.0          NaN         NaN      NaN  

[976 rows x 38 columns]

# MLR STARTS HERE

In [7]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

In [8]:
# independent variable = 'RF_1', 'RF_2', 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8'
model1 = linear_model.LinearRegression()
model1.fit(part1[['RF_1', 'RF_2', 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8']], part1.Q)
Q_pred1 = model1.predict(part2[['RF_1', 'RF_2', 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[ 1.77105908  4.55859007 -6.27643702 12.20547272] 16.71568473013339 -0.09324850277938612 218.3893563265967


In [22]:
# independent variable =  'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8'
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[-3.73656035  7.26654076  8.03442737] 25.42699217087977 -0.1195746911815565 221.0031983537895


In [10]:
# independent variable =  'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8'
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[-2.08871952  4.45997395  0.7995712   4.32051959  5.27861219] 16.21298160481291 -0.197851279642004 228.5985509967946


In [23]:
# independent variable =  'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8'
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[ 2.51132345 -0.30624472  5.32218651  5.20263586] 16.55926148231717 -0.20097753336211888 228.89666454267552


In [12]:
# independent variable =  RF_3 RF_4 RF_5 RF_6 RF_8(t-1) 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8(t-1)']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6', 'RF_8(t-1)']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[0.71064261 2.01126376 2.86830401 4.86118422 3.23788063] 8.626622760318526 -0.024699886522414394 211.43182900859634


In [13]:
# independent variable =  RF_3 RF_4 RF_5 RF_6(t-1) RF_8(t-1) 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6(t-1)', 'RF_8(t-1)']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3', 'RF_4', 'RF_5', 'RF_6(t-1)', 'RF_8(t-1)']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[-3.65078693  6.65387556  6.96105195  2.66611808  1.70086141] 3.3085443910726298 0.01791790632741319 206.98835780131745


In [14]:
# independent variable =  RF_3 RF_4 RF_5(t-1) RF_6(t-1) RF_8(t-1) 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3', 'RF_4', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3', 'RF_4', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[4.23955313 4.8260869  0.19809483 2.78693249 1.89691561] 6.18718126346802 0.05740182174497499 202.78476354157578


In [15]:
# independent variable =  RF_3 RF_4(t-1) RF_5(t-1) RF_6(t-1) RF_8(t-1) 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[8.70590092 0.02040481 0.08677344 3.02474736 1.78902198] 8.670891554116366 0.05713425482954726 202.81354284807466


In [16]:
# independent variable =  'RF_3(t-1)', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)'
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3(t-1)', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3(t-1)', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[-2.30088837  2.92221528  0.88735142  3.78682189  3.01342885] 52.576350671046924 0.21144651517093072 185.47594834640117


In [17]:
# independent variable =  RF_3(t-1) RF_4(t-1) RF_5(t-1) RF_6(t-1) RF_8(t-1) 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 't-1', 't-2', 't-3',  't-4']], part1.Q)
Q_pred1 = model1.predict(part2[[ 't-1', 't-2', 't-3','t-4']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[0.19733869 9.80478306 3.59972512 1.25721957] -1.7909357101872558 -0.07955177580477613 217.01700256613344


In [18]:
# independent variable =  RF_3(t-1) RF_4(t-1) RF_5(t-1) RF_6(t-1) RF_8(t-1) 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3','RF_4','RF_3(t-1)', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_3','RF_4','RF_3(t-1)', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[ 4.24942068  4.81715126 -0.77511001  0.53669357  0.63120899  2.54468841
  1.93048135] 6.299492149250639 0.05703564255514626 202.8241484841012


In [19]:
# independent variable =  RF_3(t-1) RF_4(t-1) RF_5(t-1) RF_6(t-1) RF_8(t-1) 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_3(t-1)', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)', 't-1']], part1.Q)
Q_pred1 = model1.predict(part2[[  'RF_3(t-1)', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-1)', 'RF_8(t-1)', 't-1']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[-0.08487993 -2.87757468  0.70166673  1.81418027  1.53874766  7.71488935] 49.11271482755336 0.21307196467306178 185.28468845374033


In [20]:
# independent variable =  RF_3(t-1) RF_4(t-1) RF_5(t-1) RF_6(t-1) RF_8(t-1) 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_8(t-2)', 'RF_3(t-1)', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-2)']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_8(t-2)' ,'RF_3(t-1)', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-2)']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[ 1.61202737 -4.6332057   5.75613263  5.50707006  1.11756263] 43.819513436565444 0.2737117226538728 178.0026795175474


In [21]:
# independent variable =  RF_3(t-1) RF_4(t-1) RF_5(t-1) RF_6(t-1) RF_8(t-1) 
model1 = linear_model.LinearRegression()
model1.fit(part1[[ 'RF_8(t-2)', 'RF_3(t-1)', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-2)']], part1.Q)
Q_pred1 = model1.predict(part2[[ 'RF_8(t-2)' ,'RF_3(t-1)', 'RF_4(t-1)', 'RF_5(t-1)', 'RF_6(t-2)']])
R2_score1 = r2_score(part2[['Q']], Q_pred1)
MSE1 = mean_squared_error(part2[['Q']], Q_pred1)
RMSE1 = np.sqrt(MSE1)
print(model1.coef_, model1.intercept_, R2_score1, RMSE1)

[ 1.61202737 -4.6332057   5.75613263  5.50707006  1.11756263] 43.819513436565444 0.2737117226538728 178.0026795175474
